production:
  hostname: tools.shinjiezumi.work
  stage: production
  roles:
    - app
  deploy_path: /usr/share/nginx/html/deployer/tools
  #  branch: master
  branch: feature/add-cicd
  user: github
  identityFile: ~/.ssh/github_ssh_key
